data:
  name: Burgers
  datapath: './burgers_data_samples.mat'
  total_num: 270
  offset: 0
  n_sample: 25
  nx: 128
  nt: 100
  sub: 1
  sub_t: 1
 
model:
  layers: [16, 24, 24, 32, 32]
  modes1: [15, 12, 9, 9]
  modes2: [15, 12, 9, 9]
  fc_dim: 128
  act: gelu
  num_pad: 4

train:
  batchsize: 20
  v: 0.01
  epochs: 501
  milestones: [100,200,300,400,500]
  base_lr: 0.001
  scheduler_gamma: 0.5
  gps_loss: 0.0001
  ic_loss: 0.0
  f_loss: 1.0
  xy_loss: 5.0
  save_dir: 'burgers'
  save_name: 'burgers-sym-25_new.pt'
  
test:
  batchsize: 20
  batch_size: 1
  n_sample: 20
  offset: 90
  ckpt: 'checkpoints/burgers-FDM/burgers-pretrain-eqn.pt'
